In [ ]:
data = """Deep Learning is transforming the way machines understand, learn and interact with complex data. Deep learning mimics neural networks of the human brain, it enables computers to autonomously uncover patterns and make informed decisions from vast amounts of unstructured data.Neural network consists of layers of interconnected nodes or neurons that collaborate to process input data. In a fully connected deep neural network data flows through multiple layers where each neuron performs nonlinear transformations, allowing the model to learn intricate representations of the data.

In a deep neural network the input layer receives data which passes through hidden layers that transform the data using nonlinear functions. The final output layer generates the model’s prediction.Types of neural networks
Feedforward neural networks (FNNs): They are the simplest type of ANN, where data flows in one direction from input to output. It is used for basic tasks like classification.
Convolutional Neural Networks (CNNs): They are specialized for processing grid-like data, such as images. CNNs use convolutional layers to detect spatial hierarchies, making them ideal for computer vision tasks.
Recurrent Neural Networks (RNNs): They are able to process sequential data, such as time series and natural language. RNNs have loops to retain information over time, enabling applications like language modeling and speech recognition. Variants like LSTMs and GRUs address vanishing gradient issues.
Generative Adversarial Networks (GANs): This consist of two networks—a generator and a discriminator—that compete to create realistic data. GANs are widely used for image generation, style transfer and data augmentation.
Autoencoders: They are unsupervised networks that learn efficient data encodings. They compress input data into a latent representation and reconstruct it, useful for dimensionality reduction and anomaly detection.
Transformer Networks: It has revolutionized NLP with self-attention mechanisms. Transformers excel at tasks like translation, text generation and sentiment analysis, powering models like GPT and BERT.Applications
1. Computer vision
In computer vision, deep learning models enable machines to identify and understand visual data. Some of the main applications of deep learning in computer vision include:

Object detection and recognition: Deep learning models are used to identify and locate objects within images and videos, making it possible for machines to perform tasks such as self-driving cars, surveillance and robotics.
Image classification: Deep learning models can be used to classify images into categories such as animals, plants and buildings. This is used in applications such as medical imaging, quality control and image retrieval.
Image segmentation: Deep learning models can be used for image segmentation into different regions, making it possible to identify specific features within images.
2. Natural language processing (NLP)
In NLP, deep learning model enable machines to understand and generate human language. Some of the main applications of deep learning in NLP include:

Automatic Text Generation: Deep learning model can learn the corpus of text and new text like summaries, essays can be automatically generated using these trained models.
Language translation: Deep learning models can translate text from one language to another, making it possible to communicate with people from different linguistic backgrounds.
Sentiment analysis: Deep learning models can analyze the sentiment of a piece of text, making it possible to determine whether the text is positive, negative or neutral.
Speech recognition: Deep learning models can recognize and transcribe spoken words, making it possible to perform tasks such as speech-to-text conversion, voice search and voice-controlled devices.
3. Reinforcement learning
In reinforcement learning, deep learning works as training agents to take action in an environment to maximize a reward. Some of the main applications of deep learning in reinforcement learning include:

Game playing: Deep reinforcement learning models have been able to beat human experts at games such as Go, Chess and Atari.
Robotics: Deep reinforcement learning models can be used to train robots to perform complex tasks such as grasping objects, navigation and manipulation.
Control systems: Deep reinforcement learning models can be used to control complex systems such as power grids, traffic management and supply chain optimization.
Advantages
High accuracy: Deep Learning algorithms can achieve state-of-the-art performance in various tasks such as image recognition and natural language processing.
Automated feature engineering: Deep Learning algorithms can automatically discover and learn relevant features from data without the need for manual feature engineering.
Scalability: Deep Learning models can scale to handle large and complex datasets and can learn from massive amounts of data.
Flexibility: Deep Learning models can be applied to a wide range of tasks and can handle various types of data such as images, text and speech.
Disadvantages
Here are some of the main challenges in deep learning:

Data availability: It requires large amounts of data to learn from. For using deep learning it's a big concern to gather as much data for training.
Computational Resources: For training the deep learning model, it is computationally expensive because it requires specialized hardware like GPUs and TPUs.
Interpretability: Deep learning models are complex, it works like a black box. It is very difficult to interpret the result.
Overfitting: when the model is trained again and again it becomes too specialized for the training data leading to overfitting and poor performance on new data."""

In [ ]:
# now providing tokens for each word
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([data])

In [ ]:
# displaying
tokenizer.word_index

{'and': 1,
 'to': 2,
 'learning': 3,
 'deep': 4,
 'data': 5,
 'of': 6,
 'the': 7,
 'it': 8,
 'models': 9,
 'can': 10,
 'in': 11,
 'as': 12,
 'for': 13,
 'such': 14,
 'a': 15,
 'like': 16,
 'text': 17,
 'neural': 18,
 'networks': 19,
 'are': 20,
 'used': 21,
 'tasks': 22,
 'is': 23,
 'learn': 24,
 'from': 25,
 'language': 26,
 'making': 27,
 'applications': 28,
 'image': 29,
 'be': 30,
 'reinforcement': 31,
 'complex': 32,
 'model': 33,
 'they': 34,
 'images': 35,
 'possible': 36,
 'machines': 37,
 'layers': 38,
 'input': 39,
 'computer': 40,
 'vision': 41,
 'speech': 42,
 'recognition': 43,
 'nlp': 44,
 'some': 45,
 'main': 46,
 'training': 47,
 'understand': 48,
 'with': 49,
 'human': 50,
 'amounts': 51,
 'network': 52,
 'that': 53,
 'using': 54,
 'specialized': 55,
 'processing': 56,
 'natural': 57,
 'generation': 58,
 'into': 59,
 'sentiment': 60,
 'identify': 61,
 'include': 62,
 'perform': 63,
 'control': 64,
 'or': 65,
 'process': 66,
 'flows': 67,
 'through': 68,
 'where': 69,
 

In [ ]:
# number of unique words
length = len(tokenizer.word_index)
print(length)

344


**Separating the sentences**

In [ ]:
# for finding all the sentences in the data
input_sequence = []
for sentence in data.split('\n'):
  #print(sentence)
  #print(tokenizer.texts_to_sequences([sentence])[0])

  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  # now here we are making our input like
  # ip-[4] , op-[3]
  # ip-[4,3], op-[23]
  # ip=[4,3,23], op-[112] and so on...

  for i in range(1,len(tokenized_sentence)):
     input_sequence.append(tokenized_sentence[:i+1])

In [ ]:
input_sequence

[[4, 3],
 [4, 3, 23],
 [4, 3, 23, 112],
 [4, 3, 23, 112, 7],
 [4, 3, 23, 112, 7, 113],
 [4, 3, 23, 112, 7, 113, 37],
 [4, 3, 23, 112, 7, 113, 37, 48],
 [4, 3, 23, 112, 7, 113, 37, 48, 24],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5, 4],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5, 4, 3],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5, 4, 3, 115],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5, 4, 3, 115, 18],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5, 4, 3, 115, 18, 19],
 [4, 3, 23, 112, 7, 113, 37, 48, 24, 1, 114, 49, 32, 5, 4, 3, 115, 18, 19, 6],
 [4,
  3,
  23,
  112,
  7,
  113,
  37,
  48,
  24,
  1,
  114,
  49,
  32,
  5,
  4,
  3,
  115,
  18,
  19,
  6,
  7],
 [4,
  3,
  23,
  112,


**Zero Padding**

In [ ]:
# now applying zero padding as we know in supervised learning
# the size of inputs must be same

# so we gonna fine max length of each sentence for applying zero padding

max_len = max([len(x) for x in input_sequence])
print(max_len)

# this can also written as
#lengths = []
#for x in input_sequence:
#   lengths.append(len(x))
#max_len = max(lengths)


84


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequence,maxlen = max_len,padding = 'pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   4,   3],
       [  0,   0,   0, ...,   4,   3,  23],
       [  0,   0,   0, ...,   3,  23, 112],
       ...,
       [  0,   0,   0, ..., 343, 103, 344],
       [  0,   0,   0, ..., 103, 344,  96],
       [  0,   0,   0, ..., 344,  96,   5]], dtype=int32)

**Separating the input and output**

In [ ]:
x = padded_input_sequences[:,:-1]


In [ ]:
x

array([[  0,   0,   0, ...,   0,   0,   4],
       [  0,   0,   0, ...,   0,   4,   3],
       [  0,   0,   0, ...,   4,   3,  23],
       ...,
       [  0,   0,   0, ...,   1, 343, 103],
       [  0,   0,   0, ..., 343, 103, 344],
       [  0,   0,   0, ..., 103, 344,  96]], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]
y

array([  3,  23, 112,   7, 113,  37,  48,  24,   1, 114,  49,  32,   5,
         4,   3, 115,  18,  19,   6,   7,  50, 116,   8, 117, 118,   2,
       119, 120, 121,   1, 122, 123, 124,  25, 125,  51,   6, 126,   5,
        18,  52, 127,   6,  38,   6, 128, 129,  65, 130,  53, 131,   2,
        66,  39,   5,  11,  15, 132, 133,   4,  18,  52,   5,  67,  68,
       134,  38,  69, 135, 136, 137,  70, 138, 139,   7,  33,   2,  24,
       140, 141,   6,   7,   5,  15,   4,  18,  52,   7,  39,  71, 142,
         5, 143, 144,  68, 145,  38,  53, 146,   7,   5,  54,  70, 147,
         7, 148,  72,  71, 149,   7, 150, 151,  73,   6,  18,  19,  18,
        19, 153,  34,  20,   7, 154, 155,   6, 156,  69,   5,  67,  11,
        74, 157,  25,  39,   2,  72,   8,  23,  21,  13, 158,  22,  16,
        75,  18,  19,  77,  34,  20,  55,  13,  56, 159,  16,   5,  14,
        12,  35,  77, 160,  76,  38,   2, 161, 162, 163,  27, 164, 165,
        13,  40,  41,  22,  18,  19,  78,  34,  20,  79,   2,  6

In [ ]:
x.shape

(821, 83)

In [ ]:
y.shape

(821,)

In [ ]:
#If you have 345 total classes (possible tokens/words),Each label (e.g., 7) becomes a vector
#of length 345 — all zeros except a 1 at the index corresponding to that label.#
# 3 - [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = length+1)
y.shape

(821, 345)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

**Model**

In [ ]:
from tensorflow.keras.layers import Embedding,LSTM,Dense
from tensorflow.keras.models import Sequential

In [ ]:
vocal_size  = length+1
model = Sequential()
model.add(Embedding(vocal_size,100,input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(vocal_size,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [ ]:
model.build(input_shape=(None, 83))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 83, 100)        │        34,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 345)            │        52,095 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 237,195 (926.54 KB)

 Trainable params: 237,195 (926.54 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x,y,epochs=100)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.0155 - loss: 5.7698
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0470 - loss: 5.2417
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0667 - loss: 5.1121
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0753 - loss: 5.0580
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0896 - loss: 4.9229
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0840 - loss: 4.8456
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1203 - loss: 4.6672
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1509 - loss: 4.4822
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1664 - loss: 4.3614
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1793 - loss: 4.1417
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2060 - loss: 3.9326
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accurac

In [ ]:
text = 'feedforward'
# tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
# padding
padded_token_text = pad_sequences([token_text], maxlen=84,padding='pre')
print(padded_token_text)
# predict
model.predict(padded_token_text)


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0 152]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step


array([[5.32833759e-08, 1.64771918e-05, 4.38543384e-06, 3.94388381e-03,
        2.98608618e-04, 5.92193741e-04, 6.18491322e-04, 3.37826175e-04,
        1.77032154e-04, 1.16510682e-06, 5.84969348e-05, 1.06694524e-05,
        1.86198031e-05, 1.14549402e-05, 4.44079196e-05, 8.22444126e-05,
        3.76241951e-05, 3.32263269e-04, 9.61790621e-01, 7.56145513e-04,
        4.82393370e-05, 3.17452617e-07, 2.40751993e-04, 1.08929544e-06,
        2.50968970e-08, 2.30353498e-06, 1.10545276e-04, 6.61223430e-06,
        1.49057041e-05, 2.41842201e-07, 5.32097388e-08, 2.49830773e-03,
        2.14092724e-04, 1.06407003e-06, 7.26948841e-04, 4.50915607e-08,
        8.56717861e-08, 1.51222014e-06, 9.47686931e-05, 4.88226942e-06,
        1.42677702e-04, 5.72160388e-06, 2.27232917e-08, 9.65253799e-04,
        6.26733299e-06, 7.95841261e-05, 5.49927279e-07, 1.36159406e-05,
        5.91536889e-07, 3.88972057e-06, 2.52240488e-06, 3.15385296e-05,
        1.37395007e-04, 6.96670613e-05, 1.02138010e-05, 7.003760

In [ ]:
model.predict(padded_token_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


(1, 345)

In [ ]:
import numpy as np
position = np.argmax(model.predict(padded_token_text))
for word,index in tokenizer.word_index.items():
  if index == position:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
neural


In [ ]:
# more systemmetical model
text = 'what is data augmentation'
for i in range (20):
  # tokenizer
  tokenized_text = tokenizer.texts_to_sequences([text])
  # padding
  padded_tokenized_text = pad_sequences(tokenized_text,maxlen=84,padding = 'pre')
  # prediction
  prediction = model.predict(padded_tokenized_text)
  # finding the highesr prob. word
  pos = np.argmax(prediction)
  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
what is data augmentation deep
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
what is data augmentation deep learning
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
what is data augmentation deep learning model
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
what is data augmentation deep learning model it
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
what is data augmentation deep learning model it is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
what is data augmentation deep learning model it is computationally
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
what is data augmentation deep learning model it is computationally expensive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
what is data augmentation deep learning model it is computationally expensive because
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
what is data augmentation deep learning model it is computationally expensive because it
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
what is data augmentation deep learning model it is computationally expensive bec